#### seq2seq example run through

* SRC from [higepon](https://gist.github.com/higepon/eb81ba0f6663a57ff1908442ce753084) to get to grips with the API.
* TF guide for NMT [here](https://www.tensorflow.org/tutorials/seq2seq)
* Documentation [here](https://www.tensorflow.org/api_guides/python/contrib.seq2seq)

In [1]:
# Import statements
import numpy as np
import tensorflow as tf
seq2seq = tf.contrib.seq2seq

/Users/tom/miniconda3/envs/py35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)


In [3]:
# Parameter setup
hparams = tf.contrib.training.HParams(batch_size=3,
                                      encoder_length=4,
                                      decoder_length=5,
                                      num_units=6,
                                      src_vocab_size=7,
                                      tgt_vocab_size=9,
                                      embedding_size=8,
                                      optimizer="Adam",
                                      learning_rate=0.01,
                                      max_gradient_norm=5.0,
                                      beam_width=9,
                                      use_attention=False,
                                     )

# Symbol for starting to decode
tgt_sos_id = 7

# Symbol for end of decode process
tgt_eos_id = 8

# Refresh graph
tf.reset_default_graph()

# Variable initialiser
initializer = tf.contrib.layers.xavier_initializer()

### Encoder declaration

In [4]:
# Encoder input placeholder is time major [enc_len, batch_size]
enc_inputs = tf.placeholder(dtype=tf.int32, shape=(hparams.encoder_length, hparams.batch_size), name="enc_input")

# Encoder embedding matrix [can be initialised with GloVe] [src_vocab_size, embedding_size]
enc_embeddings = tf.get_variable(shape=(hparams.src_vocab_size, hparams.embedding_size), name="enc_embed")

# Lookup enc_input in the embedding matrix [enc_len, batch_size, embedding_size]
enc_input_embs = tf.nn.embedding_lookup(params=enc_embeddings, ids=enc_inputs)

# LSTM encoder
lstm_encoder_cell = tf.nn.rnn_cell.BasicLSTMCell(hparams.num_units)

##### LSTM Computation graph for Encoding

In [5]:
# Run Dynamic RNN: outputs [enc_len, batch_size, num_units]: enc_state [batch_size, num_units]
encoder_outputs, encoder_state = tf.nn.dynamic_rnn(cell=lstm_encoder_cell, 
                                                   inputs=enc_input_embs, 
                                                   time_major=True,
                                                   dtype=tf.float32
                                                  )

### Decoder declaration

In [6]:
# Decoder input placeholder is time major [dec_len, batch_size]
# Decoder lengths [batch_size]

# For training we use 100% teacher forcing so each time step uses Ground Truth inputs. Inference is 100% free running
dec_inputs = tf.placeholder(dtype=tf.int32, shape=(hparams.decoder_length, hparams.batch_size),name="dec_inputs")
dec_lens = tf.placeholder(dtype=tf.int32, shape=(hparams.batch_size), name="dec_len")

# Decoder embedding matrix [can be initialised with GloVe] [tgt_vocab_size, embedding_size]
dec_embeddings = tf.get_variable(shape=(hparams.tgt_vocab_size, hparams.embedding_size), name="dec_embed")

# Lookup dec_inputs 
dec_input_embs = tf.nn.embedding_lookup(params=dec_embeddings, ids=dec_inputs)

# LSTM decoder
lstm_decoder_cell = tf.nn.rnn_cell.BasicLSTMCell(hparams.num_units)

# Projection layer between LSTM outputs and vocab size for softmax learning model
projection_layer = tf.layers.Dense(units=hparams.tgt_vocab_size, activation=None, kernel_initializer=initializer, use_bias=False)

##### seq2seq decoding declaration

In [7]:
# Declare decoding helper
dec_helper = seq2seq.TrainingHelper(inputs=dec_input_embs, sequence_length=dec_lens, time_major=True, name="dec_helper")

if hparams.use_attention:
    # Attention states are batch major [batch_size, max_time, num_units]
    attention_states = tf.transpose(encoder_outpus, [1, 0, 2])

    luong_attn_mechanism = seq2seq.LuongAttention(num_units=hparams.num_units, 
                                                 memory=attention_states, 
                                                 memory_sequence_length=None
                                                 )

    decoder_cell = seq2seq.AttentionWrapper(cell=lstm_decoder_cell,
                                            attention_mechanism=luong_attn_mechanism,
                                            attention_layer_size=hparams.num_units
                                            )

    dec_initial_state = lstm_decoder_cell.zero_state(hparams.batch_size, tf.float32).clone(cell_state=encoder_state)
else:
    # Decoding with dec_helper when encoder output feeds to decoder input
    dec_initial_state = encoder_state

decoder = seq2seq.BasicDecoder(cell=lstm_decoder_cell,
                               helper=dec_helper,
                               initial_state=dec_initial_state,
                               output_layer=projection_layer)

##### LSTM Computation graph for Decoding with seq2seq helpers

In [8]:
# s2s version of decoding
# final_outputs.rnn_output : RNN states [batch_size, dec_len, tgt_vocab_size]
# final_outputs.sample_id  : Argmax for IDs from RNN outputs [batch_size, dec_len]
# final_state              : Final RNN states [batch_size, num_units]
# final_seq_lens           : Decoded sequences [batch_size, dec_len]

final_outputs, _final_state, _final_seq_lens = seq2seq.dynamic_decode(decoder)

output_logits = final_outputs.rnn_output

In [9]:
print("rnn_output.shape=", final_outputs.rnn_output.shape)
print("sample_id.shape=", final_outputs.sample_id.shape)
print("final_state=", _final_state)
print("final_sequence_lengths.shape=", _final_seq_lens.shape)

rnn_output.shape= (3, ?, 9)
sample_id.shape= (3, ?)
final_state= LSTMStateTuple(c=<tf.Tensor 'decoder/while/Exit_3:0' shape=(3, 6) dtype=float32>, h=<tf.Tensor 'decoder/while/Exit_4:0' shape=(3, 6) dtype=float32>)
final_sequence_lengths.shape= (3,)


##### Setup loss and training operations

In [10]:
# Training targets for decoder [batch_size, dec_len]
dec_targets = tf.placeholder(dtype=tf.int32, shape=(hparams.batch_size, hparams.decoder_length))

# Setup loss computation [could also use seq2seq.sequence_loss]: https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/sequence_loss
smxe_loss = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=dec_targets,
                                                           logits=output_logits,
                                                           name="smxe_loss")

# Reduce loss in batch by mean
loss_ = tf.reduce_mean(smxe_loss)

# Training operations
global_step = tf.Variable(initial_value=0, 
                          name="global_step", 
                          trainable=False, 
                          collections=[tf.GraphKeys.GLOBAL_STEP,
                                       tf.GraphKeys.GLOBAL_VARIABLES]
                         )

train_op = tf.contrib.layers.optimize_loss(loss=loss_,
                                           global_step=global_step,
                                           learning_rate=hparams.learning_rate,
                                           optimizer=hparams.optimizer,
                                           clip_gradients=hparams.max_gradient_norm,
                                          )

##### TF Interactive session

In [11]:
sess = tf.InteractiveSession()

Example training data

In [12]:
# Encoder 

tweet1 = np.array([1, 2, 3, 4])
tweet2 = np.array([0, 5, 6, 3])

# Make batch data [TIME MAJOR]
train_encoder_inputs = np.stack((tweet1, tweet2, tweet1), axis=0).astype(np.int32).T

print("Tweets")
print(train_encoder_inputs)

Tweets
[[1 0 1]
 [2 5 2]
 [3 6 3]
 [4 3 4]]


In [13]:
# Decoder

training_decoder_input1 = [tgt_sos_id, 2, 3, 4, 5]
training_decoder_input2 = [tgt_sos_id, 5, 6, 4, 3]

training_target_label1 = [2, 3, 4, 5, tgt_eos_id]
training_target_label2 = [5, 6, 4, 3, tgt_eos_id]

training_target_labels = np.stack((training_target_label1, 
                                    training_target_label1, 
                                    training_target_label1), axis=0).astype(np.int32)
print("Replies")
print(training_target_labels)

training_decoder_inputs = np.stack((training_decoder_input1, 
                                    training_decoder_input2, 
                                    training_decoder_input1), axis=0).astype(np.int32).T
print("Inputs")
print(training_decoder_inputs)

training_decoder_lens = np.ones((hparams.batch_size), dtype=int) * hparams.decoder_length

print("Decoder lengths")
print(training_decoder_lens)

Replies
[[2 3 4 5 8]
 [2 3 4 5 8]
 [2 3 4 5 8]]
Inputs
[[7 7 7]
 [2 5 2]
 [3 6 3]
 [4 4 4]
 [5 3 5]]
Decoder lengths
[5 5 5]


##### Training

In [14]:
sess.run(tf.global_variables_initializer())

In [15]:
for i in range(100):
    _, loss_val = sess.run(fetches=[train_op, loss_],
                           feed_dict={
                               enc_inputs: train_encoder_inputs,
                               dec_targets: training_target_labels,
                               dec_inputs: training_decoder_inputs,
                               dec_lens: training_decoder_lens
                           })
    print(loss_val)

2.18588
2.15841
2.1305
2.10127
2.07033
2.03751
2.0029
1.96689
1.93016
1.89365
1.85838
1.82512
1.79429
1.76578
1.73917
1.71383
1.68912
1.66458
1.63994
1.61514
1.59027
1.56549
1.54099
1.5169
1.49332
1.47027
1.44781
1.42595
1.40439
1.38238
1.35925
1.33508
1.31048
1.28596
1.26154
1.23677
1.21112
1.18444
1.15707
1.12972
1.10279
1.07593
1.04861
1.02121
0.99462
0.969204
0.944472
0.919904
0.89562
0.872007
0.848958
0.826036
0.80322
0.780929
0.759335
0.7382
0.717399
0.697144
0.677581
0.658512
0.639726
0.621262
0.603187
0.585408
0.56782
0.550452
0.53339
0.516663
0.500262
0.484205
0.468542
0.453319
0.438556
0.424261
0.410443
0.39711
0.384264
0.371897
0.359994
0.348538
0.337523
0.326941
0.31679
0.307058
0.297733
0.288793
0.280216
0.271974
0.264041
0.256389
0.248993
0.241834
0.234896
0.228166
0.221638
0.215306
0.209168
0.203224
0.197475
0.191924


#### Model is now trained, test with inference on toy task

In [16]:
# Inference helper. Similar to training helper but free running over teacher forcing
tiled_sos_id = tf.fill([hparams.batch_size], tgt_sos_id)

inference_helper = seq2seq.GreedyEmbeddingHelper(embedding=dec_embeddings,
                                                 start_tokens=tiled_sos_id,
                                                 end_token=tgt_eos_id)

# Inference Decoder runs the decoding process with free running inputs
inference_decoder = seq2seq.BasicDecoder(cell=lstm_decoder_cell,
                                         helper=inference_helper,
                                         initial_state=dec_initial_state,
                                         output_layer=projection_layer)

# Limit realistic RNN length
maxit = tf.round(tf.reduce_max(hparams.encoder_length) * 2)

outputs, _, _ = seq2seq.dynamic_decode(inference_decoder, maximum_iterations=maxit)
translations = outputs.sample_id


In [17]:
# Input tweets
inference_encoder_inputs = train_encoder_inputs

In [19]:
replies = sess.run(fetches=[translations], 
                   feed_dict={
                       enc_inputs: inference_encoder_inputs
                   })

print(replies)

[array([[2, 3, 4, 5, 8],
       [2, 3, 4, 5, 8],
       [2, 3, 4, 5, 8]], dtype=int32)]


##### Well thats only 66% correct, lets try a Beam search


In [20]:
# Beam Search
# Replicate encoder infos beam_width times
decoder_initial_state = tf.contrib.seq2seq.tile_batch(
    dec_initial_state, multiplier=hparams.beam_width)

# Define a beam-search decoder
inference_decoder = tf.contrib.seq2seq.BeamSearchDecoder(
        cell=lstm_decoder_cell,
        embedding=dec_embeddings,
        start_tokens=tf.fill([hparams.batch_size], tgt_sos_id),
        end_token=tgt_eos_id,
        initial_state=decoder_initial_state,
        beam_width=hparams.beam_width,
        output_layer=projection_layer,
        length_penalty_weight=0.0)

# Dynamic decoding
outputs, _, _ = tf.contrib.seq2seq.dynamic_decode(
    inference_decoder, maximum_iterations=maxit)

# Convert to [batch_siz]
translations = tf.transpose(outputs.predicted_ids,[0, 2, 1]) 

In [22]:
replies = sess.run(translations, feed_dict={
                       enc_inputs inference_encoder_inputs,
                       dec_lens: training_decoder_lens
                   })
print(replies[0])

[[[2 3 2 2 2 2 2 2 2]
  [3 4 2 3 3 8 3 3 3]
  [4 5 3 4 8 8 4 3 4]
  [5 8 4 8 8 8 5 4 5]
  [8 8 5 8 8 8 5 5 3]
  [8 8 8 8 8 8 8 8 8]]

 [[2 3 2 2 2 2 2 2 2]
  [3 4 2 3 3 8 3 3 3]
  [4 5 3 4 8 8 4 3 4]
  [5 8 4 8 8 8 5 4 5]
  [8 8 5 8 8 8 5 5 3]
  [8 8 8 8 8 8 8 8 8]]

 [[2 3 2 2 2 2 2 2 2]
  [3 4 2 3 3 8 3 3 3]
  [4 5 3 4 8 8 4 3 4]
  [5 8 4 8 8 8 5 4 5]
  [8 8 5 8 8 8 5 5 3]
  [8 8 8 8 8 8 8 8 8]]]


In [ ]:
np.shape(replies[0])

In [ ]:
np.transpose(replies[0], [0, 2, 1])

In [ ]:
replies[0].beam_search_decoder_output._fields

In [ ]:
sess.close()